### ISSUE TITLE
Explain extism_alloc a little bit in the readme

### ISSUE THREAD

**Issue by G4Vi** [extism/c-pdk#15]
Make it clear when `extism_free` is needed or not needed.

**Comment by bhelx** [comment]
Thanks! I feel like we could use a little more somewhere about what this memory channel is for exactly and that would help a little. Maybe a more formal explanation. I think you need to know how extism works to understand when you'd want to free it. But I'll let @zshipko weigh in on what he thinks.

**Comment by zshipko** [comment]
Maybe we could have something on the concepts page about how memory works and link to it from the README?

We should specifically mention that Extism allocated memory will be reset before each call so `free` is only needed to recycle memory within a single call. This means values you know you're done with should be freed just to avoid wasting resources but there won't be any memory leaks if you forget.

**Comment by G4Vi** [comment]
> Maybe we could have something on the concepts page about how memory works and link to it from the README?

A short snippet with a more in-depth explanation linked sounds best to me.

**Comment by G4Vi** [comment]
Added https://extism.org/docs/concepts/memory to the concepts. Now I just have to link it here.
